# ------------------------------------------------------------------------------------
# ----------- Pre upgrade steps (backup, download from s3) -------------------------
# ------------------------------------------------------------------------------------

- hosts: windows
  roles:
     - iis
  tags: "API-TEST"

- hosts: local
  roles:
     - put-folder-s3

- hosts: local
  tasks:
  - debug:
      msg: " test-api "
# ---------------------------------------------- Finished the Deploy ------------------------------------